var data = [
  "Timed Images|JavaScript application that displays images at specified intervals|http://www.serve.com/hotsyte/wildman/url_timed_images/url_timed_images.html",
	"The Database Search|JavaScript application that searches simple databases|http://www.serve.com/hotsyte/wildman/db_search/search_frames.html",
	"Active Images|JavaScript application that uses the image object to create dynamic image changes|http://www.serve.com/hotsyte/wildman/active_images/activeimages.html",
	"Autoscroll|JavaScript application that scrolls web pages for you|http://www.serve.com/hotsyte/wildman/autoscroll/auto_scroll.html",
	"Left-Right Scroll|JavaScript application that scrolls web pages from left to right|http://www.serve.com/hotsyte/wildman/autoscroll/auto_scroll.html",
	"Drop Box|JavaScript application that facilitates web site navigstion with &lt;SELECT&gt; lists|http://www.serve.com/hotsyte/wildman/dropbox/selfrm.html",
	"E-mail Submission|JavaScript application that sends commands to LISTSERV mail servers|http://www.serve.com/hotsyte/wildman/email_submit/email_submit.html",
	"Membership Application|JavaScript application that allows users to apply for online membership|http://www.serve.com/hotsyte/wildman/members_app/member_app.html",
	"HotSyte- The JavaScript Resource|Home page for tutorials, examples, scripts, links, instruction, Netscape articles, editorials, links, newsgroups, JavaScript books, a JavaScript web ring, and web development software|http://www.serve.com/hotsyte/",
	"Instruction|JavaScript instruction, tutorials, links, examples, and downloadable or cut-and-paste scripts|http://www.serve.com/hotsyte/instruct.html",
	"Interaction|JavaScript newsgroups, bulletin boards, mailing lists|http://www.serve.com/hotsyte/interact.html",
	"Editorials|JavaScript articles with tips, dos and don'ts, and other advice about JavaScript|http://www.serve.com/hotsyte/editor.html",
	"Wildman's Archive|Free JavaScript scripts and applications by the legendary Wildman Timothy Hobbs|http://www.serve.com/hotsyte/wildman/",
	"The HotSyte Reserve|Cool scripts you can download, compliments of the HotSyte webmaster|http://www.serve.com/hotsyte/reserve.html",
	"Publications|Books, e-zines, and other JavaScript-related publications|http://www.serve.com/hotsyte/books.html",
	"Web Gear|The HotSyte download center for the latest browsers, plug-ins, and other cool web development software|http://www.serve.com/hotsyte/tools.html",
	"Resources|JavaScript documentation, sites of interest, resources, reference, JavaScript research, and general information|http://www.serve.com/hotsyte/genref.html",
	"Station HTML|Links to sites offering HTML intruction and reference|http://www.serve.com/hotsyte/html.html",
	"JavaScript Image Object|How to use the image object to enhance web page interactivity|http://www.serve.com/hotsyte/079701.html",
	"JavaScript, For Language Harmony|How to use JavaScript for multi-lingual sites|http://www.serve.com/hotsyte/079702.html",
	"Steppin' In The Pooptoy|Pointers to keep your JavaScript beneficial to web site visitors|http://www.serve.com/hotsyte/069701.html",
	"JavaScript DON'Ts: onMouseOver and You|An article about what not to do with the onMouseOver event|http://www.serve.com/hotsyte/039701.html",
	"Interacting With Users: Alert(), Confirm(), and Prompt() Methods|How to use dialog boxes to increase web page interactivity|http://www.serve.com/hotsyte/019704.html",
	"Employing \"Anti-explosion\" Tactics at Your JavaScript Site|How to avoid JavaScript errors|http://www.serve.com/hotsyte/019701.html",
	"JavaScript: What's The Buzz?|An introduction to the concept and utility of JavaScript|http://www.serve.com/hotsyte/019702.html",
	"Cyber Date Profile|JavaScript application that uses the cookie property to maintain the client state|http://www.serve.com/hotsyte/cybrdate.html",
	"Bank Reserve|Simple JavaScript database application|http://www.serve.com/hotsyte/database.html",
	"E-Lit 101|JavaScript/CGI application that lets	users request files and receive them via e-mail|http://www.serve.com/hotsyte/elit101.html",
	"JavaScript E-mail|JavaScript application that allows users to send e-mail without a CGI program|http://www.serve.com/hotsyte/jsemail.html",
	"The Arguments Array|Learn about the JavaScript argument object and its array|http://www.serve.com/hotsyte/argument.html",
	"Synapse|JavaScript application and memory game where players must match pairs by memory and can choose skill levels|http://www.serve.com/hotsyte/download/synapse.zip",
	"Fruit Shopper|JavaScript application that demonstrates the basics of HTML form validation|http://www.serve.com/hotsyte/fruit.html",
	"Pythagorean Theorem Solver|JavaScript application that solves for the missing sides of right triangles|http://www.serve.com/hotsyte/triangle.html",
	"Browser Identifier|JavaScript application that provides users with information about their browsers|http://www.serve.com/hotsyte/browser.html",
	"Routing Browsers|JavaScript application that routs visitors to web pages according to browser|http://www.serve.com/hotsyte/routing.html",
	"Zodiac Profiler|JavaScript application that demonstrates the utility of arrays|http://www.serve.com/hotsyte/zodiac.html",
	"Shopping Cart|JavaScript application that facilitates online shopping|http://www.serve.com/hotsyte/wildman/shopping_cart/shop_cart._intro.html",
	"JavaScript Guestbook|JavaScript application that uses cookies so users can read and write comments about the hosting web site|http://www.serve.com/hotsyte/wildman/guestbook/gb.html",
	"Active Map|JavaScript application that demonstrates the utility of the image object with a map graphic|http://www.serve.com/hotsyte/wildman/active_map/active_map.html",
	"Jukebox|JavaScript application that allows users to select from a list of audio clips|http://www.serve.com/hotsyte/wildman/jukebox/jukewindow.html",
	"Scratchpad|JavaScript application that allows users to e-mail webmasters feedback|http://www.serve.com/hotsyte/wildman/scratchpad/open_scratchpad.html"
]